In [151]:
import google.auth
import pymupdf
import re
import pandas as pd
import os

from dotenv import load_dotenv
from sqlalchemy import create_engine
from google import genai
from google.genai import types
from collections import Counter
from langchain_postgres.vectorstores import PGVector
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from pgvector.sqlalchemy import Vector
from sqlalchemy import text

In [132]:
load_dotenv()

True

## Read Pdf

Analisar el patron del documento para maximizar los resultados de la busqueda y el resumen

In [121]:
def get_chapters(ruta_pdf: str, incluir_referencias: bool = True) -> list[dict]:
    """
    Fragmenta un artículo académico por capítulos con títulos en romanos y mayúsculas
    (I. INTRODUCCIÓN, II. CONCEPTUALIZACIÓN, ...). Pensado para PDFs a dos columnas.
    Retorna dicts: numero, etiqueta, titulo, contenido, pagina_inicio, pagina_fin.
    """
    romano_valido = re.compile(r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$")
    patron_titulo = re.compile(r"^([IVXLC]+)\.\s+([^a-záéíóúñ]+)$")
    patron_referencias = re.compile(r"^(REFERENCIAS|BIBLIOGRAF[ÍI]A|REFERENCES)\s*$")
    valores = {"I": 1, "V": 5, "X": 10, "L": 50, "C": 100}

    def romano_a_entero(r):
        if not romano_valido.match(r):
            return None
        total = 0
        for i, c in enumerate(r):
            v = valores[c]
            total += -v if i + 1 < len(r) and v < valores[r[i + 1]] else v
        return total

    with pymupdf.open(ruta_pdf) as doc:
        paginas = [p.get_text() for p in doc]

    normalizar = lambda l: re.sub(r"\d+", "", l).strip()
    zona = lambda t: [normalizar(l) for l in t.splitlines()[:4] + t.splitlines()[-4:]]
    conteo = Counter(n for t in paginas for n in set(zona(t)) if n)
    repetidas = {l for l, c in conteo.items() if c >= 2 and len(l) >= 15}

    lineas = []
    for num, texto in enumerate(paginas, start=1):
        texto = re.sub(r"(\w)-\n(\w)", r"\1\2", texto)
        todas = texto.splitlines()
        for j, l in enumerate(todas):
            l = l.strip()
            en_zona = j < 4 or j >= len(todas) - 4
            if not l or l.isdigit() or (en_zona and normalizar(l) in repetidas):
                continue
            lineas.append((l, num))

    fragmentos, actual, siguiente, preambulo = [], None, 1, []
    i = 0
    while i < len(lineas):
        linea, pagina = lineas[i]
        m = patron_titulo.match(linea)
        es_titulo = m and romano_a_entero(m.group(1)) == siguiente
        es_refs = patron_referencias.match(linea) and actual is not None

        if es_titulo or es_refs:
            if actual:
                fragmentos.append(actual)
            if es_refs:
                if not incluir_referencias:
                    actual = None
                    break
                numero, etiqueta, titulo = None, "", linea.strip()
            else:
                numero, etiqueta, titulo = siguiente, m.group(1), m.group(2).strip()
                while i + 1 < len(lineas):
                    sig = lineas[i + 1][0]
                    if sig.isupper() and len(sig) < 60 and not patron_titulo.match(sig):
                        titulo += " " + sig
                        i += 1
                    else:
                        break
                siguiente += 1
            actual = {"numero": numero, "etiqueta": etiqueta, "titulo": titulo,
                      "contenido": "", "pagina_inicio": pagina, "pagina_fin": pagina}
        elif actual:
            actual["contenido"] += linea + "\n"
            actual["pagina_fin"] = pagina
        else:
            preambulo.append(linea)
        i += 1

    if actual:
        fragmentos.append(actual)

    for f in fragmentos:
        f["contenido"] = re.sub(r"(?<![.:])\n(?=[a-záéíóúñ(«])", " ", f["contenido"]).strip()

    if preambulo:
        fragmentos.insert(0, {"numero": 0, "etiqueta": "", "titulo": "Resumen / Preámbulo",
                              "contenido": "\n".join(preambulo),
                              "pagina_inicio": 1,
                              "pagina_fin": fragmentos[0]["pagina_inicio"] if fragmentos else 1})
    return fragmentos

In [122]:
path = r'/home/sebas/Documents/projects/opensource/rag-agent/agent/resources/Dialnet-UnaMiradaALaInteligenciaArtificial-7894426.pdf'

In [123]:
fragmentos = get_chapters(path)
df = pd.DataFrame(fragmentos)
columnas_en = {
    "numero": "number",
    "etiqueta": "label",
    "titulo": "title",
    "contenido": "content",
    "pagina_inicio": "start_page",
    "pagina_fin": "end_page",
}

capitulos = get_chapters(path)
df = pd.DataFrame(capitulos).rename(columns=columnas_en)
df

,number,label,title,content,start_page,end_page
0,0.0,,Resumen / Preámbulo,Vol. 2 / Núm. 3 / enero - junio de 2015; pág. ...,1,1
1,1.0,I,INTRODUCCIÓN,En este documento se describirá un estado del ...,1,1
2,2.0,II,CONCEPTUALIZACIÓN,"La palabra inteligencia, etimológicamente se d...",1,2
3,3.0,III,HISTORIA DE LA INTELIGENCIA ARTIFICIAL,"A través de los años, el ser humano se ha preo...",2,3
4,4.0,IV,CLASES DE INTELIGENCIA ARTIFICIAL,Existen diveras categorias de inteligencia hum...,3,4
5,5.0,V,APLICACIONES DE LA INTELIGENCIA ARTIFICIAL,La inteligencia artificial ha sido utilizada e...,4,5
6,6.0,VI,CONCLUSIONES,Con el anterior panorama general sobre intelig...,5,5
7,NaN,,REFERENCIAS,"[1]\nReal Academia Española, «Inteligencia,» D...",5,5

In [124]:
_,PROJECT_ID = google.auth.default()
PROJECT_ID

'superagentycs-dev'

In [157]:
genai_client = genai.Client(
    enterprise=True, 
    project=PROJECT_ID, 
    location='global'
)

In [ ]:
def get_summary(text : str) -> str:
    
    response = genai_client.models.generate_content(
        model="gemini-3.8-flash", 
        contents=f"Dame un resumen muy corto acerca de este capitulo : {text}"
    )

    return response.text

In [166]:
dimensionality = 768
embeddings = GoogleGenerativeAIEmbeddings(
    model="gemini-embedding-2",
    project=PROJECT_ID,
    output_dimensionality=dimensionality,
    vertexai=True
)

## Summary Chapters

In [128]:
df['enhanced_summary'] = df['content'].apply(get_summary)
df.head()

,number,label,title,content,start_page,end_page,enhanced_summary
0,0.0,,Resumen / Preámbulo,Vol. 2 / Núm. 3 / enero - junio de 2015; pág. ...,1,1,Aquí tienes un resumen muy corto:\n\nEl artícu...
1,1.0,I,INTRODUCCIÓN,En este documento se describirá un estado del ...,1,1,Este documento presenta un estado del arte sob...
2,2.0,II,CONCEPTUALIZACIÓN,"La palabra inteligencia, etimológicamente se d...",1,2,**Resumen:**\n\nEl texto explica que la inteli...
3,3.0,III,HISTORIA DE LA INTELIGENCIA ARTIFICIAL,"A través de los años, el ser humano se ha preo...",2,3,**Resumen:**\n\nEl texto aborda la evolución h...
4,4.0,IV,CLASES DE INTELIGENCIA ARTIFICIAL,Existen diveras categorias de inteligencia hum...,3,4,"A diferencia de la **inteligencia humana**, qu..."

In [167]:
df["embedding"] = df["enhanced_summary"].apply(lambda t: embeddings.embed_query(t))
df.head()

,number,label,title,content,start_page,end_page,enhanced_summary,embedding
0,0.0,,Resumen / Preámbulo,Vol. 2 / Núm. 3 / enero - junio de 2015; pág. ...,1,1,Aquí tienes un resumen muy corto:\n\nEl artícu...,"[-0.026663352, 0.0015331028, -0.029846944, 0.0..."
1,1.0,I,INTRODUCCIÓN,En este documento se describirá un estado del ...,1,1,Este documento presenta un estado del arte sob...,"[-0.03691173, -0.017748224, -0.039401595, -0.0..."
2,2.0,II,CONCEPTUALIZACIÓN,"La palabra inteligencia, etimológicamente se d...",1,2,**Resumen:**\n\nEl texto explica que la inteli...,"[-0.014437694, 0.020469595, -0.018497491, 0.01..."
3,3.0,III,HISTORIA DE LA INTELIGENCIA ARTIFICIAL,"A través de los años, el ser humano se ha preo...",2,3,**Resumen:**\n\nEl texto aborda la evolución h...,"[-0.04380985, 0.0008681383, -0.02427634, -0.00..."
4,4.0,IV,CLASES DE INTELIGENCIA ARTIFICIAL,Existen diveras categorias de inteligencia hum...,3,4,"A diferencia de la **inteligencia humana**, qu...","[-0.002686019, 0.007830093, 0.0048449566, 0.02..."

In [161]:
PG_USER=os.environ.get("PG_USER")
PG_PASSWORD=str(os.environ.get("PG_PASSWORD"))
PG_HOST=str(os.environ.get("PG_HOST"))
PG_DATABASE=os.environ.get("PG_DATABASE")
PG_PORT=str(os.environ.get("PG_PORT"))

In [162]:
connection_string = f"postgresql://{PG_USER}:{PG_PASSWORD}@{PG_HOST}:{PG_PORT}/{PG_DATABASE}"
engine = create_engine(connection_string)

In [144]:
## RUN sudo apt install postgresql-1X-pgvector

In [163]:
with engine.begin() as conn:
    conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))

In [188]:
collection_name = "my_docs"
vector_store = PGVector(
    embeddings=embeddings,
    collection_name=collection_name,
    connection=engine,
    use_jsonb=True,
)

In [189]:
vector_store.add_embeddings(
    texts=df["enhanced_summary"].tolist(),
    embeddings=df["embedding"].apply(list).tolist(),
    metadatas=df[["label", "title", "content", "start_page", "end_page"]].to_dict("records"),
)

['8b174e9e-dca8-4838-83c9-1964655eb856',
 '9c41170b-9780-477c-b2eb-05df297cb2b6',
 '9c7a782a-4a2d-473c-aeab-81e345bf667c',
 '7f1c42b7-8cd4-4626-8738-19a8e5caf62f',
 '32d477c6-b429-4d54-a735-6c1ccab1ae61',
 '3bf8d2c3-44f8-4f5d-a89d-0b40bb899d16',
 '196fbd84-dd40-46dc-8b78-5a05fe8aea7a',
 '270012cc-3f78-4c62-9b1e-914bc1830732']

In [192]:
results = vector_store.similarity_search("Cual es la historia de la Inteligencia artificial", k=3)
response_documents = [i.metadata for i in results]
response_documents

[{'label': 'I',
  'title': 'INTRODUCCIÓN',
  'content': 'En este documento se describirá un estado del arte acerca de la inteligencia arficial como tendencia tecnológica que está impactando diferentes sectores.\nEn la sección II del documento se dará a conocer una definición de inteligencia artificial, su idea principal de estudio y el porqué surgió esta ciencia.\nEn la sección III se tiene la cronología de la Inteligencia Artificial, sus inicios, el desarrollo que ha tenido a traves de los años, y algunas de sus características.\n*\nMichael Estid Alvarado Rojas. Estudiante de Ingeniería de Sistemas. Corporación Universitaria Republicana.\nEn la sección IV se describen los dos tipos de inteligencia artificial que se tienen en cuenta en la actualidad, que son al Inteligencia Artificial convencional y la computacional, se habla a fondo de estos dos términos, sus parámetros y sus métodos de estudio.\nEn la sección V se resaltan aplicaciones de interés y se presentan algunas conclusiones sobre este estado del arte.',
  'end_page': 1,
  'start_page': 1},
 {'label': '',
  'title': 'Resumen / Preámbulo',
  'content': 'Vol. 2 / Núm. 3 / enero - junio de 2015; pág. 27-31\nUNA MIRADA A LA INTELIGENCIA ARTIFICIAL\nArtificial Intelligence (AI) at a Glance\nMICHAEL ESTID ALVARADO ROJAS*\nRecibido: 20 de Enero de 2015. Aceptado: 20 de Abril de 2015\nRESUMEN\nEn este documento se dan a conocer los conceptos básicos, la historia, las clases e información relevante acerca de la\ninteligencia artificial. En resumen, la inteligencia artificial se define como la ciencia que tiene un enfoque importante en\nel desarrollo de programas o máquinas, que son capaces de razonar solo para la solución de un problema, y se añade\na esta tener la capacidad de ser más eficiente que un ser humano.\nPalabras clave:\nalabras clave:\nalabras clave:\nalabras clave:\nalabras clave: inteligencia artificial, sistemas expertos, aplicaciones, resolución de problemas.\nABSTRACT\nIn this document are given to learn the basics, history, classes, and most relevant information about artificial intelligence.\nIn sum, the artificial intelligence is defined as the science that has one major approach in the development of programs\nor machines, which are capable of reasoning alone for the solution of problem, and added to this have the ability to be\nmore efficient than a human.\nKeywords:\nKeywords:\nKeywords:\nKeywords:\nKeywords: artificial intelligence, expert systems, applications, problem solving.',
  'end_page': 1,
  'start_page': 1},
 {'label': 'III',
  'title': 'HISTORIA DE LA INTELIGENCIA ARTIFICIAL',
  'content': 'A través de los años, el ser humano se ha preocupado por su capacidad de razomiento y su habilidad para analizar, planear y dar una solución a un problema. Desde ese entonces en paralelo también se ha buscado la manera de crear sistemas para reproducir habilidades mentales que solo poseen los humanos, y que de tal manera se pueda realizar de una manera más simple algunos procesos.\nLa noción de la Inteligencia artificial tiene sus inicios con el escritor e inventor húngaro y ajedrecista Johann Wolfgang Von Kempelen, quien diseño un androide llamado el Turco que aparentemente jugaba ajedrez simulando ser un mecanismo automatico [5], sin embargo era operado por una persona oculta en el mecanismo; sin embargo gracias a esta idea farsa que simulaba ser un automata, fue objeto de inspiración para construir verdaderos automatas como el caso de el automata\nEl Ajedrecista construido en 1912 por Leonardo\nTorres Quevedo, invento que operaba sin intervención humana considerado como el primer juego por computador de la historia [6].\nEn 1816 fue descrita la máquina analítica realizada por Charles Babbage [5], matemático ingles y cientifico protoinformático, quine contribuyo con la historia de la computación ya que el motor analitico de Babbage tenia la capacidad de construir tablas de logaritmos y de funciones trigonométricas evaluando polinomios por aproximación.\nCien años más tarde se construyeron computadoras aplicando el mismo principio.\nA partir del siglo XIX se conciben las analogías biológicas y fenomenológicas para el estudio de la mente humana. Es así, como a partir de la segunda mitad del siglo XIX, la noción de mecanismo transformo el poder heurístico con la formalización del concepto de «computación» [5].\nLa comunidad cientifica empezo a manejar el término y concepto de Inteligencia Artificial en el año 1950 gracias a Alan Mathison Turing, matemático, lógico, científico de la computación, criptógrafo, filósofo, maratonista británico. Dadas sus contribuciones y en su artículo denominado\nMaquinaria Computacional e Inteligencia [7\nVol. 2 / Núm. 3 / enero - junio de 2015; pág. 27-31\nAlgunos afirman que los comienzos de la inteligencia artificial ocurrieron al definirse la neurona, en 1943, como un elemento binario con varias entradas y salidas [8]. En el año de 1956 se volvió a retomar el tema y se establecieron las bases de la\nInteligencia Artificial como un campo independiente dentro de la informática.\nBajo el contexto histórico referenciado por Alan\nTuring la inteligencia artificial se ha definido desde entonces bajo diferentes perspectivas como sistemas que piensan como humanos, sistemas que piensan racionalmente, sistemas que actúan como humanos y sistemas que actúan racionalmente.\nRichard Ernest Bellman, matemático y doctor de la universidad de Princeton, destaca en su publicación An introduction to artificial intelligence: can computers think? que: La automatización de actividades que vinculamos con procesos de pensamiento humano, actividades como la toma de decisiones, resolución de problemas, aprendizaje [9].\nJohn Haugeland, profesor de filosofía de la\nUniversidad de Chicago en su publicación Artificial Intelligence: The Very Idea, dice: El nuevo y excitante esfuerzo de hacer que las computadoras piensen... máquinas con mentes, en el más amplio sentido literal [10].\nEl mismo año en 1985, Eugene Charniak, profesor de la Universidad de Brown y Drew\nMcDermott profesor de la Universidad de Yale afirmaron que la inteligencia artificial es el estudio de las facultades mentales mediante el uso de modelos computacionales [11].\nEn años recientes, Raymond Kurzweil inventor estadounidense especializado en Ciencias de la\nComputación e Inteligencia Artificial, actualmente director de ingeniería en Google, afirma que el arte de desarrollar máquinas con capacidad para realizar funciones que cuando son realizadas por personas requieren de inteligencia [12], en concordancia que la inteligencia artificial son sistemas que actuan con humanos.\nNeil Nilsson, profesor de la Universidad de\nStanford del departamento de ciencias de la computación afirma que la inteligencia artificial está relacionada con conductas inteligentes en artefactos [13] y cuando se relacionan las conductas se habla se un sistema que actua racionalmente.\nSe puede afirmar que la inteligencia artificial se ha venido concibiendo bajo las características humanas tales como pensar, actuar y a su vez adaptarse y autocorregirse.\nUn agente inteligente se puede definir como lo definio Rusell, como una entidad que percibe y actúa sobre un entorno [14] y fue en 1987 el año en que se describieron caracterisiticas relevantes para el uso de un agente inteligente:\n1. Creencias e intenciones (actitudes mentales).\n2. Obtención de conocimiento (aprender).\n3. Resolver problemas.\n4. Entendimiento y lógica.\n5. Planificación, predicción y evaluación de alternativas.\n6. Delimitar sus propias habilidades y conocimientos.\n7. Distinción de situaciones.\n8. Crear conceptos e ideas.\n9. Generalizar.\n10.Percibir y modelar el mundo exterior.\n11.Aplicar su propio lenguaje y símbolos para su propio entendimiento.\nDe acuerdo a las caracteristicias mencionadas anteriormente, la Inteligencia Artificial tambien ha sido empleada como una técnica de software que los programas utilizan para dar solución óptima a algún tipo de problema, tratando de asemejar el comportamiento inteligente que se observa en la naturaleza, en especial la de los seres humanos.',
  'end_page': 3,
  'start_page': 2}]